# Generated by Django 5.0.4 on 2024-08-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day_or_night',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night')], max_length=5, null=True),
        ),
    ]
