# Generated by Django 5.0.4 on 2024-08-11 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_course_day_or_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prices',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='frontend.price'),
        ),
    ]
